# apply: kubectl apply -f k8s-goherokuauth.yaml
# check: kubectl get all
# check on service: curl http://localhost:30000/api/v1/auth

apiVersion: v1
kind: Service
metadata:
  name: goherokuauth-service
spec:
  type: NodePort
  selector:
    app: goherokuauth
  ports:
      # targetPort is Pod/container's port. port is where other pods (in same cluster) connect to.
    - port: 80
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goherokuauth-deployment
  labels:
    app: goherokuauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goherokuauth
  template:
    metadata:
      labels:
        app: goherokuauth
    spec:
      containers:
      - name: goherokuauth
        image: djayap/goherokuauth:latest
        ports:
        - containerPort: 8080